const quizData = [
  {
    "id": 1,
    "part": 1,
    "question": "",
    "audio": "sounds/1-01.mp3",
    "image": "images/01.png",
    "transcript": "他們在哪裡？\n(A) 銀行\n(B) 教室\n(C) 郵局",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 2,
    "part": 1,
    "question": "",
    "audio": "sounds/1-02.mp3",
    "image": "images/02.png",
    "transcript": "窗戶怎麼了？\n(A) 窗戶破了\n(B) 窗戶打開了\n(C) 窗戶不見了",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 3,
    "part": 1,
    "question": "",
    "audio": "sounds/1-03.mp3",
    "image": "images/03.png",
    "transcript": "書桌上有幾本書？\n(A) 桌子上有兩本書\n(B) 桌子上有四本書\n(C) 桌子上有十本書",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 4,
    "part": 1,
    "question": "",
    "audio": "sounds/1-04.mp3",
    "image": "images/04.png",
    "transcript": "圖片裡有什麼？\n(A) 一碗麵\n(B) 一碗飯\n(C) 一碗湯",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 5,
    "part": 1,
    "question": "",
    "audio": "sounds/1-05.mp3",
    "image": "images/05.png",
    "transcript": "這個人在做什麼？\n(A) 打籃球\n(B) 打網球\n(C) 打棒球",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 6,
    "part": 1,
    "question": "",
    "audio": "sounds/1-06.mp3",
    "image": "images/06.png",
    "transcript": "這位學生怎麼了？\n(A) 她在哭\n(B) 她在笑\n(C) 她在說話",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 7,
    "part": 1,
    "question": "",
    "audio": "sounds/1-07.mp3",
    "image": "images/07.png",
    "transcript": "牆上有什麼？\n(A) 牆上有花\n(B) 牆上有窗\n(C) 牆上有畫",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 8,
    "part": 1,
    "question": "",
    "audio": "sounds/1-08.mp3",
    "image": "images/08.png",
    "transcript": "小張在哪裡？\n(A) 他在餐廳\n(B) 他在書店\n(C) 他在辦公室",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 9,
    "part": 1,
    "question": "",
    "audio": "sounds/1-09.mp3",
    "image": "images/09.png",
    "transcript": "這位先生正在做什麼？\n(A) 他正在買菜\n(B) 他正在煮飯\n(C) 他正在洗衣服",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 10,
    "part": 1,
    "question": "",
    "audio": "sounds/1-10.mp3",
    "image": "images/10.png",
    "transcript": "圖片裡的天氣怎麼樣？\n(A) 下雨\n(B) 下雪\n(C) 晴天",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 11,
    "part": 1,
    "question": "",
    "audio": "sounds/1-11.mp3",
    "image": "images/11.png",
    "transcript": "他們正在做什麼？\n(A) 他們正在看電影\n(B) 他們正在看報紙\n(C) 他們正在唱歌兒",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 12,
    "part": 1,
    "question": "",
    "audio": "sounds/1-12.mp3",
    "image": "images/12.png",
    "transcript": "王小明怎麼去學校？\n(A) 他開車\n(B) 他走路\n(C) 他騎腳踏車",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 13,
    "part": 1,
    "question": "",
    "audio": "sounds/1-13.mp3",
    "image": "images/13.png",
    "transcript": "媽媽買了什麼？\n(A) 幾雙鞋子\n(B) 幾件衣服\n(C) 幾雙襪子",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 14,
    "part": 1,
    "question": "",
    "audio": "sounds/1-14.mp3",
    "image": "images/14.png",
    "transcript": "書包旁邊有什麼？\n(A) 一本書\n(B) 一枝筆\n(C) 一張紙",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 15,
    "part": 1,
    "question": "",
    "audio": "sounds/1-15.mp3",
    "image": "images/15.png",
    "transcript": "學生們怎麼上課？\n(A) 他們用電話上課\n(B) 他們用電視上課\n(C) 他們用電腦上課",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 16,
    "part": 1,
    "question": "",
    "audio": "sounds/1-16.mp3",
    "image": "images/16.png",
    "transcript": "月華的工作是什麼？\n(A) 她是警察\n(B) 她是醫生\n(C) 她是老師",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 17,
    "part": 1,
    "question": "",
    "audio": "sounds/1-17.mp3",
    "image": "images/17.png",
    "transcript": "老李在喝什麼？\n(A) 他在喝酒\n(B) 他在喝茶\n(C) 他在喝咖啡",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 18,
    "part": 1,
    "question": "",
    "audio": "sounds/1-18.mp3",
    "image": "images/18.png",
    "transcript": "大華正在做什麼？\n(A) 他正在讀書\n(B) 他正在寫字\n(C) 他正在聽音樂",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 19,
    "part": 1,
    "question": "",
    "audio": "sounds/1-19.mp3",
    "image": "images/19.png",
    "transcript": "這三個小孩哪個最高？\n(A) 他們一樣高\n(B) 穿短褲的女孩最高\n(C) 穿長褲的男孩最高",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 20,
    "part": 1,
    "question": "",
    "audio": "sounds/1-20.mp3",
    "image": "images/20.png",
    "transcript": "小天家裡還有哪些人？\n(A) 他家裡有爺爺和爸爸\n(B) 他家裡有奶奶和媽媽\n(C) 他家裡有媽媽和爸爸",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 21,
    "part": 1,
    "question": "",
    "audio": "sounds/1-21.mp3",
    "image": "images/21.png",
    "transcript": "這裡有什麼水果？\n(A) 西瓜和蘋果\n(B) 香蕉和西瓜\n(C) 蘋果和香蕉",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 22,
    "part": 1,
    "question": "",
    "audio": "sounds/1-22.mp3",
    "image": "images/22.png",
    "transcript": "請問，筆在哪兒？\n(A) 筆在電腦前面\n(B) 筆在紙的下面\n(C) 筆在桌子上面",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 23,
    "part": 1,
    "question": "",
    "audio": "sounds/1-23.mp3",
    "image": "images/23.png",
    "transcript": "今天天氣怎麼樣？\n(A) 今天雨很大，風也很大\n(B) 今天風很大，太陽也很大\n(C) 今天太陽很大，雨也很大",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 24,
    "part": 1,
    "question": "",
    "audio": "sounds/1-24.mp3",
    "image": "images/24.png",
    "transcript": "美美買了什麼？\n(A) 美美買了皮包和包子\n(B) 美美買了鞋子和皮包\n(C) 美美買了包子和鞋子",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 25,
    "part": 1,
    "question": "",
    "audio": "sounds/1-25.mp3",
    "image": "images/25.png",
    "transcript": "小明正在做什麼？\n(A) 他正在醫院看病\n(B) 他正在網路掛號\n(C) 他正在藥房拿藥",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 26,
    "part": 2,
    "question": "",
    "audio": "sounds/2-26.mp3",
    "image": "images/26.png",
    "transcript": "男：老師，我們這次旅行要帶什麼？\n女：那裡很冷，帶件外套吧！",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 27,
    "part": 2,
    "question": "",
    "audio": "sounds/2-27.mp3",
    "image": "images/27.png",
    "transcript": "男：我們去唱歌，好嗎？\n女：我牙齒好痛，我不想去。",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 28,
    "part": 2,
    "question": "",
    "audio": "sounds/2-28.mp3",
    "image": "images/28.png",
    "transcript": "男：你覺得桌子放在哪兒比較好呢？\n女：放在窗戶前面吧！那兒比較亮。",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 29,
    "part": 2,
    "question": "",
    "audio": "sounds/2-29.mp3",
    "image": "images/29.png",
    "transcript": "男：這個週末，你想去哪兒玩？\n女：天氣那麼熱，我想去海邊走走。",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 30,
    "part": 2,
    "question": "",
    "audio": "sounds/2-30.mp3",
    "image": "images/30.png",
    "transcript": "女：昨天阿姨拿來的那件衣服怎麼樣？\n男：太小了。",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 31,
    "part": 2,
    "question": "",
    "audio": "sounds/2-31.mp3",
    "image": "images/31.png",
    "transcript": "男：王小美長得怎麼樣？\n女：她的頭髮長長的，戴眼鏡。",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 32,
    "part": 2,
    "question": "",
    "audio": "sounds/2-32.mp3",
    "image": "images/32.png",
    "transcript": "男：請問火車站怎麼走?\n女：你一直往前走，車站在你的右邊。",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 33,
    "part": 2,
    "question": "",
    "audio": "sounds/2-33.mp3",
    "image": "images/33.png",
    "transcript": "男：您好，現在買兩個漢堡，就送牛奶，請問您要點什麼呢？\n女：我要兩個漢堡，還有，我要冰牛奶喔，謝謝！",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 34,
    "part": 2,
    "question": "",
    "audio": "sounds/2-34.mp3",
    "image": "images/34.png",
    "transcript": "男：新年快到了，你打算做什麼？\n女：我要去公園聽音樂會，一起來吧！",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 35,
    "part": 2,
    "question": "",
    "audio": "sounds/2-35.mp3",
    "image": "images/35.png",
    "transcript": "男：小姐，這件衣服是九百元，請問您還要買別的東西嗎？\n女：嗯，還有我手上這一件。",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 36,
    "part": 2,
    "question": "",
    "audio": "sounds/2-36.mp3",
    "image": "images/36.png",
    "transcript": "男：咦？你怎麼在醫院呢？\n女：我妹妹生了一個兒子，我來看他們。",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 37,
    "part": 2,
    "question": "",
    "audio": "sounds/2-37.mp3",
    "image": "images/37.png",
    "transcript": "男：聽說上個月你跟你的家人一起去旅行？\n女：不，我是自己一個人去的。",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 38,
    "part": 2,
    "question": "",
    "audio": "sounds/2-38.mp3",
    "image": "images/38.png",
    "transcript": "男：我的朋友這個週末要來找我，我可以帶他們去哪裡玩呢？\n女：你可以帶他們到棒球場，坐240號公車很快就到了。",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 39,
    "part": 2,
    "question": "",
    "audio": "sounds/2-39.mp3",
    "image": "images/39.png",
    "transcript": "男：我要去機場，請問應該怎麼去？\n女：你可以坐地鐵，前面就有地鐵站。",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 40,
    "part": 2,
    "question": "",
    "audio": "sounds/2-40.mp3",
    "image": "images/40.png",
    "transcript": "男：這件外套要五百元嗎？\n女：沒那麼貴。",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 41,
    "part": 3,
    "question": "",
    "audio": "sounds/3-41.mp3",
    "image": "images/41.png",
    "transcript": "男：這件褲子有大一點兒的嗎？\n女：黑色40號，好嗎？\n男：好，我可以試試嗎？\n女：可以，請到這裡來。\n男：請問他們現在在哪裡？",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 42,
    "part": 3,
    "question": "",
    "audio": "sounds/3-42.mp3",
    "image": "images/42.png",
    "transcript": "男：你好，我想找王老師上課用的書，請問這本書圖書館有嗎？\n女：等一下，我上網看看。這本書兩個禮拜以前已經被借走了。\n男：那怎麼辦？我還可以去哪裡借這本書？\n女：我想你現在只能去學校的書店買了。\n男：請問這位小姐認為男同學應該去哪裡找書？",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "B",
    "remark": ""
  },
  {
    "id": 43,
    "part": 3,
    "question": "",
    "audio": "sounds/3-43.mp3",
    "image": "images/43.png",
    "transcript": "男：您好，請問有什麼事嗎？\n女：你好，這張紙上寫著現在學游泳，比較便宜。\n男：是的，星期一到星期五的早上比較便宜。但是晚上來學，就和平常一樣了。\n女：我知道了，我可以白天來上課。\n男：請問什麼時候學游泳比較便宜？",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 44,
    "part": 3,
    "question": "",
    "audio": "sounds/3-44.mp3",
    "image": "images/44.png",
    "transcript": "男：老師，明天我們在哪裡上課？\n女：明天我們要上網，所以要去電腦教室上課。\n男：電腦教室怎麼走？\n女：電腦教室就在圖書館樓上。\n男：請問電腦教室在哪裡？",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 45,
    "part": 3,
    "question": "",
    "audio": "sounds/3-45.mp3",
    "image": "images/45.png",
    "transcript": "男：請問十點二十分的火車開了嗎？\n女：現在都二十五分了，早就開了。\n男：幾點還有車？\n女：二十分鐘以後就有車了。\n男：請問這位先生可以坐什麼時候的火車？",
    "options": ["(A)", "(B)", "(C)"],
    "answer": "C",
    "remark": ""
  },
  {
    "id": 46,
    "part": 4,
    "question": "",
    "audio": "sounds/4-46.mp3",
    "image": "",
    "transcript": "男：媽，你看見我的課本嗎？\n女：書桌那裡沒有嗎？\n男：找過了，都沒有。等一下就要上課了，真糟糕。\n女：不是放在書桌上，就是跟字典放在一起，你去看看。\n男：這位太太的意思是什麼？",
    "options": ["（A）她要兒子再找找","（B）課本不在書桌上","（C）她把課本收起來了","（D）書桌上放了本字典"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 47,
    "part": 4,
    "question": "",
    "audio": "sounds/4-47.mp3",
    "image": "",
    "transcript": "男：好久沒來這裡了，變了好多喔。\n女：以前這裡是漂亮的風景，現在這裡到處都是人。\n男：人多不好嗎？\n女：我喜歡安靜的環境。\n男：這位小姐最後的意思是什麼？",
    "options": ["（A）這裡很吵","（B）這裡人不多","（C）這裡的環境很好","（D）這裡的風景很美"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 48,
    "part": 4,
    "question": "",
    "audio": "sounds/4-48.mp3",
    "image": "",
    "transcript": "男：為什麼我買給妳的裙子，妳一件都沒穿過？\n女：如果是在生小孩以前，我應該~都會穿。\n男：妳又沒變胖，現在穿也一樣好看啊！\n女：穿褲子比較方便照顧小孩。\n男：這位小姐的意思是什麼？",
    "options": ["（A）穿褲子比較好看","（B）這些裙子太小了","（C）她不喜歡穿裙子了","（D）穿裙子時不方便照顧小孩"],
    "answer": "D",
    "remark": ""
  },
  {
    "id": 49,
    "part": 4,
    "question": "",
    "audio": "sounds/4-49.mp3",
    "image": "",
    "transcript": "男：請進，有什麼事嗎？\n女：老闆，我最近總是覺得很累、很不舒服。我想請假。\n男：妳想請多久呢？\n女：如果可以的話，我想請一個月；但是如果不行，兩個星期也可以。\n男：這位小姐希望老闆答應她什麼事？",
    "options": ["（A）讓她休息一個月","（B）讓她的工作少一點","（C）兩星期後，可以休息幾天","（D）一個月後，讓她離開公司"],
    "answer": "A",
    "remark": ""
  },
  {
    "id": 50,
    "part": 4,
    "question": "",
    "audio": "sounds/4-50.mp3",
    "image": "",
    "transcript": "男：喂，媽，請寄一些錢給我，我要買衣服。\n女：衣服不是都帶去了嗎？為什麼還要買？\n男：我變胖了，那些衣服都穿不下了。\n女：你才去念了半年的書就變胖了，我想那裡的東西一定很好吃。\n男：這個兒子打電話跟母親說什麼？",
    "options": ["（A）沒收到衣服","（B）沒錢吃東西","（C）沒錢買衣服","（D）請母親寄衣服"],
    "answer": "C",
    "remark": ""
  }
];
